# Generated by Django 6.0.2 on 2026-02-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLife', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('duration', models.DecimalField(decimal_places=1, max_digits=4)),
                ('category', models.CharField(choices=[('DEV', 'Development/Coding'), ('BIZ', 'Business/Admin'), ('LRN', 'Learning/Research'), ('DES', 'Design/UI')], max_length=3)),
                ('description', models.TextField()),
                ('log_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
