# Generated by Django 6.0.2 on 2026-02-11 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyLife', '0002_worklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worklog',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
